name: 🐾 Estilo Código

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: 🐯 Obtener código del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Usar Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: 🦒 Instalar dependencias
        run: npm install

      - name: 👀 Buscar errores
        run: npm run lint
